### ISSUE TITLE
[Suggestion] Use configurable set of characters to populate tag map

### ISSUE THREAD

**Issue by ryankask** [johnlindquist/AceJump#124]
I use [avy](https://github.com/abo-abo/avy) for emacs and it allows you to choose which characters should be used to populate the keys of the tag map (ie the characters you would type to jump to a certain location).

For example, I only want to use keys on the home row to select where to jump to but since I use a custom keyboard layout, it would be nice to be able to be able to configure this.

What do you think?

**Comment by breandan** [comment]
This is possible, with the caveat that *if* we stick to two-letter tags, the number of tags that can be assigned is limited to a maximum of `Math.pow(NUM_TAGS, 2)` (although considerably less in practice, since we remove all tags that occur in plaintext). I think we could try to prioritize tags in home-row positions, since we already do a bunch of keyboard optimizations. But we should probably let the user override these settings.

**Comment by breandan** [comment]
Deployed in 6b3f036. AceJump now supports tagging with alphanumeric symbols of your choice. Please update to the latest version and remember: if you assign too few symbols, AceJump will not work correctly. There is currently no validation on the input field.
