### ISSUE TITLE
Searches the entire file

### ISSUE THREAD

**Issue by unlocomqx** [johnlindquist/AceJump#209]
On PhpStorm, the plugin searches the entire file and not just the visible area

> PhpStorm 2017.3.3 EAP
> Build #PS-173.4301.15, built on January 10, 2018
> JRE: 1.8.0_152-release-1024-b11 amd64
> JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> Windows 10 10.0

**Comment by breandan** [comment]
This behavior is intentional. If you search for a string and pretty "Tab", you can scroll to search results throughout the file, in a manner similar to <kbd>Ctrl</kbd>+<kbd>F</kbd>, <kbd>Enter</kbd>. We have made recent improvements to the search that should alleviate #161, and are working on a restricted search feature that will only highlight a small number of matches on screen (#210).
