### ISSUE TITLE
feature request: jump forward/backward

### ISSUE THREAD

**Issue by stephencheng** [johnlindquist/AceJump#223]
I am from vim sneak experience and I really love the convenience of using ";" to go to first match, type it again forward for the next match, "," to go reverse direction.

Details could be found here:
https://github.com/justinmk/vim-sneak

Is it possible to add this feature and that would make it the best plugin in intellij.

Thanks

**Comment by breandan** [comment]
Interesting. This would remove the ability to search for strings containing `;` and `,`. Maybe we add this as a user-configurable setting.

**Comment by stephencheng** [comment]
not really. when you start search, it will do increamental search. once you typed 2 chars, it will highlight the found positions and highlight them, then it will enter the command mode. At this time, you should be able to use ; and , to go forward and backward.

I tried the plugin, I do not understand why it can not search the out side of the screen buffer. Is it the design that it only search within the current screen scope? or I have got it wrong?

Thanks

**Comment by breandan** [comment]
Not sure what you mean by "Command Mode", maybe there is a misunderstanding here. After you activate AceJump, you can type any number of characters on your keyboard. Typing characters which occur sequentially inside the editor will narrow down the results, and typing the adjacent tag characters will select the tag.

Unless you are using **Word Mode** there is no limitation to the number of matches to the screen boundary (although this has been proposed #217). Since `;` and `,` occur naturally inside the editor, and we do not use these for tags, if we were to reuse them for navigation, this behavior would conflict with the search behavior unless we exposed this as a user-configurable setting.

**Comment by stephencheng** [comment]
You are right, there is no command mode in there. I have got the point. I have found the non-vim way achieving this:

use word mode -> enter -> cmd+g (forward search) | cmd+shift+g (backward search)

Thanks for making such a great plugin
