### ISSUE TITLE
Any possibility to constrain search to start of word or camelCase?

### ISSUE THREAD

**Issue by dchenbecker** [johnlindquist/AceJump#42]
Love the plugin, but one thing that I would love is a mode or config setting to just search for characters right after non-alphanumeric characters (e.g. start of words). Sometimes the tag soup that results from, say, jumping to "e" is a bit tough to dig through.

**Comment by breandan** [comment]
This would be a nice feature to have. There should be a better tag-search mechanism, maybe one that tries to retain some similarity with the underlying word. There are 26*26=676 two letter tags to assign, and we can try to match them to a unique substring inside each word, or fall back to a unique camelcase, or even any sequential characters with gaps (evenly distributing tags to words throughout the screen). 

There should be a way to assign tags such that no two-letter tag matches any two letter string inside the screen. There are plenty of unused two letter strings that do not occur naturally. For example "XX", "XY", "GF". If we enumerate all unique two letter strings for each screenful, and retain the complement of that set for tagging, then users can directly type a word on the screen, and we can dynamically narrow down the targets after each keystroke without any tag collisions.

Another optimization would be to highlighting unique one- and two- character strings on the screen as soon as AceJump is triggered (without waiting for the search character). If the user types any of these unique one- or two-character strings, there is only one possible jump point. If the user starts typing a non-unique string, we can recycle tags using nearby letters on the keyboard, or do a camel-case search like autocompletion in IntelliJ IDEA.

Finally, we should try to prioritize tags by ease of typing instead of alphabetically. It's much easier to type "FF" than "YM". Vimium realizes this and uses adjacent (or nearby) character sequences to avoid finger travel distance. To implement this would need some kind of Comparator with a keyboard distance metric. Need to think about this one a little.

Let me know if you have any other ideas.

**Comment by favetelinguis** [comment]
Me to would like this, just as it works in Emacs. Then it also makes sense to extend the seach over multiple buffers so you can use Acejump to jump between splits!

**Comment by breandan** [comment]
All of the above features have been implemented, or deemed unworkable. Closing.
