### ISSUE TITLE
Build instruction should be updated

### ISSUE THREAD

**Issue by dc-psv** [johnlindquist/AceJump#55]
Please update build instruction to build on Mac OS. And please share latest version via Jetbrains Plugin Repo.

Thank you!

**Comment by breandan** [comment]
The issue with building the plugin on Mac OS X should be fixed (just run `./gradlew buildPlugin` from the repo directory). There hasn't been any major updates or features since the current release, just internal refactoring and Kotlin-related migration. We'll push an update to the JetBrains Plugin Repository as soon as we figure out what's going on with #53, #51, #47...

**Comment by breandan** [comment]
I stand corrected. It looks like the plugin was never published after merging #43.

**Comment by breandan** [comment]
[Done](https://github.com/johnlindquist/AceJump/issues/53#issuecomment-197686309).
