### ISSUE TITLE
Mode for multi character search

### ISSUE THREAD

**Issue by eliasbagley** [johnlindquist/AceJump#58]
It would be awesome if there was a second hotkey that would allow you to enter a mutli-character search target. So instead of showing the jump target as soon as I press `Ctrl+; e`, it waits to show them until something like `Crtrl+ALT+; e a ENTER` and then only shows jump targets on `ea`. I think this could speed up editing since it's much more likely that only a single digit jump target will be shown.

**Comment by ryankask** [comment]
This is a great idea.

I find that I really only use `avy-goto-char-2` in emacs: https://github.com/abo-abo/avy#avy-goto-char-2

**Comment by abcarroll** [comment]
Same here.  This plugin is useless to me because of that reason.  Thus far I always just CTRL+F and naturally start typing the first *few* letters of what I want.  

I do appreciate the time and effort put into the plugin, but stopping, waiting, and scanning the page for meaningless markers seems like a waste of time to me.

**Comment by breandan** [comment]
This is now implemented in AceJump 3.0 Beta. You don't need to do anything special, since it's seemlessly integrated with the existing tagging mechanism. Feel free to try it out and leave your feedback. Thanks!

https://github.com/johnlindquist/AceJump/releases/tag/3.0.0
