### ISSUE TITLE
Feature request: let enter more than 1 letter

### ISSUE THREAD

**Issue by klikh** [johnlindquist/AceJump#7]
Typing 1 letter produces really a lot of results. On a big screen I usually have to press Enter twice or three times to highlight the usage I need.
It would be great if the search box could accept several letters: even 2 letters would dramatically decrease the number of results.

**Comment by breandan** [comment]
Multi-character search now implemented in AceJump 3.0 Beta. You don't even need a separate mode, since it's seamless integrated with the existing tagging mechanism - just activate AceJump and start typing 1-N characters. Feel free to give it a try and submit your feedback. Thanks!

https://github.com/johnlindquist/AceJump/releases/tag/3.0.0
