### ISSUE TITLE
What is the purpose of a white box without text?

### ISSUE THREAD

**Issue by ksdev-pl** [johnlindquist/AceJump#94]
Hi

Is it normal that when entering the text it is not visible in the "white box" visible in the screenshot (I've entered a letter "m")? If yes, maybe this box is not necessary?

The version of AceJump is 3.0.0 in  PhpStorm 2016.2.2.

![screenshot from 2016-11-02 09-32-35](https://cloud.githubusercontent.com/assets/4216259/19921854/196fe6b8-a0e0-11e6-8d74-5ca212bd07c3.png)

Thanks for your work.

**Comment by breandan** [comment]
Right now, the only purpose of the white box is to indicate when "target mode" is enabled. If you press <kbd>Ctrl</kbd>+<kbd>;</kbd> or whichever key is mapped to `AceJumpAction` twice, it will select the word at the target, instead of just moving the cursor after jumping. We should be able to do away with the white box, as long as we have another way to visually indicate target mode activation. Suggestions welcome!

**Comment by ksdev-pl** [comment]
Thank you for explanation, didn't know about the target mode.

Maybe a two-color caret instead of a box, so it would not cover the code under it? But it's not very important, I can live with a box. Please close the issue if you wish - or maybe someone will have a better idea?
