### ISSUE TITLE
Alternative shortcut doesn't work with target mode

### ISSUE THREAD

**Issue by anglee** [johnlindquist/AceJump#99]
#After upgrading from 2.0.13 to 3.0.2, I found the keyboard shortcut I use (`⌘ + ;`) no longer worked. I realized I had to add it back by going to the preferences>Keymap (if the behavior of removing user specified shortcut was intentional, I wish there was a release note so I didn't have to panic). Anyway, `⌘ + ;` worked.

However, if I hit `;` twice to start target mode (red box), the box didn't turn red and the word is not selected after jumping took place.

**Comment by anglee** [comment]
Ah, I found that this seems to be only an issue if you have more than 1 shortcuts set. If I removed the `^ + ;` (which I don't use) select mode works fine with double `⌘ + ;`

**Comment by breandan** [comment]
Hey @anglee, thanks for the report. I am aware of the issue with multiple shortcuts, although I am unsure how to fix it, as the IntelliJ Platform SDK API endpoint only supplies the first bound shortcut for an action (cf. [SearchBox.kt#L80](https://github.com/johnlindquist/AceJump/blob/master/src/main/kotlin/com/johnlindquist/acejump/ui/SearchBox.kt#L80)) - so we only read the primary shortcut. This is an issue because IntelliJ IDEA remaps the <kbd>Ctrl</kbd> modifier to <kbd>⌘</kbd> (cf. [this discussion](https://intellij-support.jetbrains.com/hc/en-us/community/posts/204146524-Inconsistent-behavior-rewriting-shortcuts-for-Mac-OS)). If you remove any secondary shortcuts, this behavior should not occur.

@yole Could you advise how to read multiple shortcuts for an action?

**Comment by yole** [comment]
Quoting from `ActionManagerImpl.getKeyboardShortcut()`:

```
    AnAction action = ActionManager.getInstance().getAction(actionId);
    final ShortcutSet shortcutSet = action.getShortcutSet();
    final Shortcut[] shortcuts = shortcutSet.getShortcuts();
```
